VERSION 0.7
FROM node:20-alpine
WORKDIR /app
RUN corepack enable

deps:
    COPY package.json pnpm-lock.yaml ./
    RUN pnpm install --frozen-lockfile

build:
    FROM +deps
    COPY --dir app assets components lib public *.json *.ts *.js *.cjs .env.production ./
    RUN pnpm run build
    SAVE ARTIFACT .next/standalone standalone
    SAVE ARTIFACT .next/static static

docker:
    RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
    # Set the correct permission for prerender cache
    RUN mkdir .next && chown nextjs:nodejs .next

    COPY public ./public

    # Automatically leverage output traces to reduce image size
    # https://nextjs.org/docs/advanced-features/output-file-tracing
    COPY --chown=nextjs:nodejs +build/standalone ./
    COPY --chown=nextjs:nodejs +build/static ./.next/static

    USER nextjs

    # -------------
    # Configuration
    # -------------
    EXPOSE 3000
    ENV PORT 3000
    ENV NODE_ENV production
    # set hostname to localhost
    ENV HOSTNAME "0.0.0.0"

    ENTRYPOINT ["node", "server.js"]

    LABEL org.opencontainers.image.source=https://github.com/ofalvai/homecooked
    SAVE IMAGE ghcr.io/ofalvai/homecooked-llm-ui:latest
