FROM node:21-alpine AS base
RUN corepack enable
# Install dependencies only when needed
FROM base AS deps

WORKDIR /app
COPY llm-ui/package.json llm-ui/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY llm-ui/ .

RUN pnpm run build

# -----------
# Final image
# -----------
FROM base AS runner

WORKDIR /app

ENV NODE_ENV production
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next && chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs


# -------------
# Configuration
# -------------
EXPOSE 3000
ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

ENTRYPOINT ["node", "server.js"]

LABEL org.opencontainers.image.source https://github.com/ofalvai/homecooked
