FROM rust:1.72-slim-bookworm AS builder

RUN apt-get update && apt-get install -y --no-install-recommends libssl-dev pkg-config libxml2-dev

WORKDIR /usr/src/

COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY embeddings embeddings
COPY focus focus
COPY gardener gardener
COPY llm-assistant llm-assistant
COPY llm-toolkit llm-toolkit
COPY speedtest-to-influx speedtest-to-influx

RUN cargo build --release --package llm-assistant

# -----------
# Final image
# -----------
FROM debian:bookworm-slim AS runner

# libxml2 needed for llm-assistant binary
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates libxml2-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /usr/src/target/release/llm-assistant bin/llm-assistant

VOLUME /data/config
ENV CONFIG /data/config/config.ini

EXPOSE 8080
ENV PORT 8080

ENTRYPOINT ["/app/bin/llm-assistant", "--config", "/data/config/config.ini", "server"]
