[package]
name = "llm-assistant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {workspace = true}
anyhow = { workspace = true }
owo-colors = { workspace = true }
tokio = { workspace = true }
async-openai = "0.12.2"
futures = "0.3.28"
async-trait = "0.1.72"
thiserror = "1.0.44"
